LinkLuaModifier("modifier_movespeed_cap", 		"modifiers/movespeed_cap", 					LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_damage_increase_30", 	"modifiers/buffs/damage_increase_30.lua", 	LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_damage_increase_50", 	"modifiers/buffs/damage_increase_50.lua", 	LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_damage_increase_60", 	"modifiers/buffs/damage_increase_60.lua", 	LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_damage_increase_70", 	"modifiers/buffs/damage_increase_70.lua", 	LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_damage_increase_80", 	"modifiers/buffs/damage_increase_80.lua", 	LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_damage_reduction_30", "modifiers/buffs/damage_reduction_30.lua", 	LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_damage_reduction_50", "modifiers/buffs/damage_reduction_50.lua", 	LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_damage_reduction_60", "modifiers/buffs/damage_reduction_60.lua", 	LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_damage_reduction_70", "modifiers/buffs/damage_reduction_70.lua", 	LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_damage_reduction_80", "modifiers/buffs/damage_reduction_80.lua", 	LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_boss_damage_reduction", "modifiers/boss_damage_reduction.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_invulnerable", "modifiers/invulnerable.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_invulnerable_res", "modifiers/invulnerable_res.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_attribute_status_resistance", "modifiers/status_resistance", LUA_MODIFIER_MOTION_NONE)
--LinkLuaModifier("modifier_custom_cleave_35", "modifiers/custom_cleave_35", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_left_the_game", "modifiers/left_the_game", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_special_hardcore", "modifiers/special_hardcore", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_neutral_upgrade_attackspeed", "modifiers/modifier_neutral_upgrade_attackspeed", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_custom_attribute_agility", "modifiers/attributes/agility", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_attribute_armor", "modifiers/attributes/armor", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_attribute_attack_damage", "modifiers/attributes/attack_damage", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_attribute_attack_speed", "modifiers/attributes/attack_speed", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_attribute_damage_outgoing", "modifiers/attributes/damage_outgoing", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_attribute_health", "modifiers/attributes/health", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_attribute_health_regen", "modifiers/attributes/health_regen", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_attribute_health_regen_percentage", "modifiers/attributes/health_regen_percentage", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_attribute_intellect", "modifiers/attributes/intellect", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_attribute_mana", "modifiers/attributes/mana", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_attribute_mana_regen", "modifiers/attributes/mana_regen", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_attribute_mana_regen_percentage", "modifiers/attributes/mana_regen_percentage", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_attribute_move_speed", "modifiers/attributes/move_speed", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_attribute_spell_amp", "modifiers/attributes/spell_amp", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_attribute_strength", "modifiers/attributes/strength", LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_disable_healing", "modifiers/disable_healing", LUA_MODIFIER_MOTION_NONE)

