LinkLuaModifier('inventory', 'inventory/inventory', LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_invulnerable", "modifiers/modifier_invulnerable", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_neutral_upgrade_attackspeed", "modifiers/modifier_neutral_upgrade_attackspeed", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_shmot_attr", "inventory/custom_shmot_attr", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gold_extra_storage", "modules/gold_extra_storage", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("dota_courier_god", "modifiers/courier/god_courier", LUA_MODIFIER_MOTION_NONE)


LinkLuaModifier("modifier_custom_attribute_agility", "modifiers/attributes/agility", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_attribute_armor", "modifiers/attributes/armor", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_attribute_attack_damage", "modifiers/attributes/attack_damage", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_attribute_attack_speed", "modifiers/attributes/attack_speed", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_attribute_damage_outgoing", "modifiers/attributes/damage_outgoing", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_attribute_health", "modifiers/attributes/health", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_attribute_health_regen", "modifiers/attributes/health_regen", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_attribute_health_regen_percentage", "modifiers/attributes/health_regen_percentage", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_attribute_incoming_damage", "modifiers/attributes/incoming_damage", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_attribute_intellect", "modifiers/attributes/intellect", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_attribute_magic_armor", "modifiers/attributes/magic_armor", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_attribute_mana", "modifiers/attributes/mana", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_attribute_mana_regen", "modifiers/attributes/mana_regen", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_attribute_mana_regen_percentage", "modifiers/attributes/mana_regen_percentage", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_attribute_move_speed", "modifiers/attributes/move_speed", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_attribute_spell_amp", "modifiers/attributes/spell_amp", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_attribute_status_resistance", "modifiers/attributes/status_resistance", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_custom_attribute_strength", "modifiers/attributes/strength", LUA_MODIFIER_MOTION_NONE)